---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gatewayapp
  name: gatewayapp
  namespace: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayapp
  template:
    metadata:
      labels:
        app: gatewayapp
    spec:
      containers:
#         - image: 192.168.174.130:32684/spring-gateway:<TAG>
        - image: 192.168.136.131:32684/spring-gateway:<TAG>
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
          imagePullPolicy: Always
          name: gatewayapp
      imagePullSecrets:
      - name: registry-regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gatewayapp
  name: gatewayapp
  namespace: springboot
spec:
  ports:
    - nodePort: 32222
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: gatewayapp
  type: NodePort
